//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBlogSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userid { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string paypassword { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string tip { get; set; }
        public string instruction { get; set; }
        public double balance { get; set; }
        public string image { get; set; }
    }
}
